#include "dispatcher.h"
#include <errno.h>
#include "../utils/connManagement/QnxConnection.h"
#include <sys/dispatch.h>

namespace dispatcher {

dispatcher::dispatcher(std::unique_ptr<connManagement::IIpcChannel> ipc) :
        _channel(std::move(ipc)) {
    _dispatcher_thread = std::thread([this] {this->run();});
}

dispatcher::~dispatcher() {
    _is_running = false;
    connManagement::QnxConnection(_channel->get_chid()).msg_send_pulse(1, _PULSE_CODE_UNBLOCK, 0);
    _dispatcher_thread.join();
}

void dispatcher::run() {
    while (_is_running) {
        connManagement::header_t header;
        int rcvid = _channel->msg_receive(&header, sizeof(connManagement::header_t));

        if (rcvid == -1) {
            //TODO logging or exception
            break;
        }

        if (rcvid == 0) { // Pulse was received
            if (header.code == _PULSE_CODE_UNBLOCK) {
                continue;
            }
            handle_event(header, rcvid);
            continue;
        }

        if ((_IO_BASE <= header.type) && (header.type <= _IO_MAX)) {
            // Some QNX IO msg generated by gns was received
            handle_qnx_io_msg(header, rcvid);
            continue;
        }

        handle_sync_msg(header, rcvid);
    }
}
void dispatcher::handle_sync_msg(connManagement::header_t header, int rcvid) {
    if (true) {//when is event subscr
        int event_id = 1;
        connManagement::chid chid = 1;
        subscribe(event_id, chid);
    }
    //maybe other forms of sync communications
}

void dispatcher::subscribe(int event_id, connManagement::chid chid) {
    if (_chid_conn_map.find(chid) == _chid_conn_map.end()) { //no connection for this chid yet
        _chid_conn_map[chid] = std::shared_ptr<connManagement::IIpcConnection>(
                new connManagement::QnxConnection(chid));
    }
    _evnt_conn_multimap[event_id].insert(_chid_conn_map[chid]);
}

void dispatcher::handle_event(connManagement::header_t header, int rcvid) {
    int evnt_id = header.code;
    int evnt_value = header.value.sival_int;
    std::cout << "dispatcher recieved following event:" << std::endl;
    std::cout << "id: " << evnt_id << std::endl;
    std::cout << "value: " << evnt_value << std::endl;

    for (auto& connection : _evnt_conn_multimap[evnt_id]) {
        connection->msg_send_pulse(1, evnt_id, evnt_value);
    }
}

void dispatcher::handle_qnx_io_msg(connManagement::header_t header, int rcvid) {
    if (header.type == _IO_CONNECT) {
        // QNX IO msg _IO_CONNECT was received; answer with EOK
        std::cout << "Dispatcher received _IO_CONNECT (sync. msg) \n" << std::endl;
        _channel->msg_reply(rcvid, EOK, nullptr, 0);
        return;
    }
    // Some other QNX IO message was received; reject it
    std::cout << "Dispatcher received unexpected (sync.) msg type = " << header.type << std::endl;
    _channel->msg_reply_error(rcvid, ENOSYS);
}

} /* namespace dispatcher */
